import "modern-css-reset/dist/reset.min.css";
import "@/app/_styles/globals.scss";
import { Noto_Sans_JP, Figtree } from "next/font/google";
import Header from "./_layouts/header/header";
import Footer from "./_layouts/footer/footer";

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-ja",
  display: "swap",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-fig",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSansJp.variable} ${figtree.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
